# Generated by Django 3.2.5 on 2023-09-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customwebcontent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webtodaysdate', models.TextField(blank=True)),
                ('webSubject', models.TextField(blank=True)),
                ('webFrom', models.TextField(blank=True)),
                ('webReceived_Time', models.TextField(blank=True)),
                ('webEmail_Body', models.TextField(blank=True)),
                ('webEmail_Bodyhtml', models.TextField(blank=True)),
                ('webcheckstatus', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
    ]
