# Generated by Django 3.2.5 on 2023-09-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogbenchsales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogtodaysdate', models.TextField(blank=True)),
                ('blogSubject', models.TextField(blank=True)),
                ('blogFrom', models.TextField(blank=True)),
                ('blogReceived_Time', models.TextField(blank=True)),
                ('blogEmail_Body', models.TextField(blank=True)),
                ('blogEmail_Bodyhtml', models.TextField(blank=True)),
                ('blogcheckstatus', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
    ]
