# Generated by Django 3.2.5 on 2023-07-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custombench',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benchfirstname', models.TextField(blank=True)),
                ('benchlastname', models.TextField(blank=True)),
                ('benchexperience', models.TextField(blank=True)),
                ('benchcurrentlocation', models.TextField(blank=True)),
                ('benchtechnology', models.TextField(blank=True)),
                ('benchrelocation', models.TextField(blank=True)),
                ('benchvisa', models.TextField(blank=True)),
                ('benchnoticeperiod', models.TextField(blank=True)),
                ('benchsalesfirstname', models.TextField(blank=True)),
                ('benchsaleslastname', models.TextField(blank=True)),
                ('benchsalescompany', models.TextField(blank=True)),
                ('benchsalesemail', models.TextField(blank=True)),
                ('benchsalesmobile', models.TextField(blank=True)),
                ('benchsalesaddress', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Custombenchsales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bstodaysdate', models.TextField(blank=True)),
                ('bsSubject', models.TextField(blank=True)),
                ('bsFrom', models.TextField(blank=True)),
                ('bsReceived_Time', models.TextField(blank=True)),
                ('bsEmail_Body', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customemailleads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todaysdate', models.TextField(blank=True)),
                ('Subject', models.TextField(blank=True)),
                ('From', models.TextField(blank=True)),
                ('Received_Time', models.TextField(blank=True)),
                ('Email_Body', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomizeBenchsalesLeads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BenchsalesFile', models.FileField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='CustomizeEmailLeads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fileupload', models.FileField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Customleads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadfirstname', models.TextField(blank=True)),
                ('leadlastname', models.TextField(blank=True)),
                ('leademail', models.TextField(blank=True)),
                ('leadusername', models.TextField(blank=True)),
                ('leadpassword', models.TextField(blank=True)),
                ('leadcompany', models.TextField(blank=True)),
                ('leadphonenumber', models.TextField(blank=True)),
                ('leadaddress', models.TextField(blank=True)),
                ('leadaddress2', models.TextField(blank=True)),
                ('leadcity', models.TextField(blank=True)),
                ('leadstate', models.TextField(blank=True)),
                ('leadzipcode', models.TextField(blank=True)),
                ('leadoccupation', models.TextField(blank=True)),
                ('leaddescription', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emailbenchsales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.TextField(blank=True)),
                ('Last_Name', models.TextField(blank=True)),
                ('Experience', models.TextField(blank=True)),
                ('Current_Location', models.TextField(blank=True)),
                ('Technology', models.TextField(blank=True)),
                ('Relocation', models.TextField(blank=True)),
                ('Visa', models.TextField(blank=True)),
                ('Notice_Period', models.TextField(blank=True)),
                ('Benchsales_First_Name', models.TextField(blank=True)),
                ('Benchsales_Last_Name', models.TextField(blank=True)),
                ('Benchsales_Company', models.TextField(blank=True)),
                ('Benchsales_Email', models.TextField(blank=True)),
                ('Benchsales_Mobile', models.TextField(blank=True)),
                ('Benchsales_Address', models.TextField(blank=True)),
                ('bcheckstatus', models.PositiveSmallIntegerField(default=1)),
                ('bdropdownlist', models.TextField(blank=True, default='Benchsales')),
                ('created_date', models.TextField(blank=True, default='2023-07-14')),
            ],
        ),
        migrations.CreateModel(
            name='Emailleadoppurtunities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refuserdate', models.TextField(blank=True)),
                ('refusertime', models.TextField(blank=True)),
                ('refusermob', models.TextField(blank=True)),
                ('refuserdetails', models.TextField(blank=True)),
                ('refemailuserdate', models.TextField(blank=True)),
                ('refemailusertime', models.TextField(blank=True)),
                ('refemailusermob', models.TextField(blank=True)),
                ('refemailuserdetails', models.TextField(blank=True)),
                ('refcheckstatus', models.PositiveSmallIntegerField(default=1)),
                ('refdropdownlist', models.TextField(default='New')),
            ],
        ),
        migrations.CreateModel(
            name='Emailsample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField(blank=True)),
                ('lastname', models.TextField(blank=True)),
                ('email', models.TextField(blank=True)),
                ('username', models.TextField(blank=True)),
                ('password', models.TextField(blank=True)),
                ('company', models.TextField(blank=True)),
                ('phonenumber', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('address2', models.TextField(blank=True)),
                ('city', models.TextField(blank=True)),
                ('state', models.TextField(blank=True)),
                ('zipcode', models.TextField(blank=True)),
                ('occupation', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('samplecheckstatus', models.PositiveSmallIntegerField(default=1)),
                ('sampledropdownlist', models.TextField(default='New')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
                ('year', models.TextField(blank=True)),
                ('filmurl', models.TextField(blank=True)),
                ('checkstatus', models.PositiveSmallIntegerField(default=1)),
                ('dropdownlist', models.TextField(default='New')),
            ],
        ),
        migrations.CreateModel(
            name='whatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.FileField(upload_to='media')),
            ],
        ),
    ]
