# Generated by Django 3.2.5 on 2023-09-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='roles',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emailbenchsales',
            name='created_date',
            field=models.TextField(blank=True, default='2023-09-13'),
        ),
    ]
