# Generated by Django 3.2.5 on 2023-10-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='film',
            name='contactdetails',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='film',
            name='keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='film',
            name='qualifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='film',
            name='responsibilities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='film',
            name='shortjobdescription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emailbenchsales',
            name='created_date',
            field=models.TextField(blank=True, default='2023-10-05'),
        ),
    ]
