# Generated by Django 3.2.5 on 2023-06-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizeEmailLeads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fileupload', models.FileField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Emailsample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField(blank=True)),
                ('lastname', models.TextField(blank=True)),
                ('email', models.TextField(blank=True)),
                ('username', models.TextField(blank=True)),
                ('password', models.TextField(blank=True)),
                ('company', models.TextField(blank=True)),
                ('phonenumber', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('address2', models.TextField(blank=True)),
                ('city', models.TextField(blank=True)),
                ('state', models.TextField(blank=True)),
                ('zipcode', models.TextField(blank=True)),
                ('occupation', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('samplecheckstatus', models.PositiveSmallIntegerField(default=1)),
                ('sampledropdownlist', models.TextField(default='New')),
            ],
        ),
    ]
