# Generated by Django 3.2.5 on 2023-09-14 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230913_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailbenchsales',
            name='created_date',
            field=models.TextField(blank=True, default='2023-09-14'),
        ),
        migrations.CreateModel(
            name='DuplicatedFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.film')),
            ],
        ),
        migrations.CreateModel(
            name='DuplicatedCustomemailleads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_Customemailleads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customemailleads')),
            ],
        ),
    ]
