# Generated by Django 3.2.5 on 2023-07-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_emailbenchsales_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customleads',
            old_name='leadoccupation',
            new_name='leadduration',
        ),
        migrations.AddField(
            model_name='customleads',
            name='leadexperience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customleads',
            name='leadinterviewtype',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customleads',
            name='leadlegalstatus',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customleads',
            name='leadlocation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customleads',
            name='leadposition',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customleads',
            name='leadrate',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customleads',
            name='leadremote',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customleads',
            name='leadworktype',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emailbenchsales',
            name='created_date',
            field=models.TextField(blank=True, default='2023-07-17'),
        ),
    ]
