# Generated by Django 3.2.5 on 2023-09-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_emailbenchsales_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombench',
            name='benchsalescity',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='custombench',
            name='benchsalesstate',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='custombench',
            name='benchsaleswebsite',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='custombench',
            name='benchsaleszipcode',
            field=models.TextField(blank=True),
        ),
    ]
