# Generated by Django 3.2.5 on 2023-07-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230717_0037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custombench',
            old_name='benchcurrentlocation',
            new_name='Duration',
        ),
        migrations.RemoveField(
            model_name='custombench',
            name='benchtechnology',
        ),
        migrations.RemoveField(
            model_name='custombench',
            name='benchvisa',
        ),
        migrations.AddField(
            model_name='custombench',
            name='Interview_Type',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='custombench',
            name='Legal_Status',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='custombench',
            name='Location',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='custombench',
            name='Position',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='custombench',
            name='Rate',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='custombench',
            name='Remote',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='custombench',
            name='Work_Type',
            field=models.TextField(blank=True),
        ),
    ]
