# Generated by Django 3.2.5 on 2023-07-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230717_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombenchsales',
            name='bscheckstatus',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customemailleads',
            name='checkstatus',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='emailbenchsales',
            name='created_date',
            field=models.TextField(blank=True, default='2023-07-21'),
        ),
    ]
