# Generated by Django 3.2.5 on 2023-10-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20231013_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='customemailleads',
            name='companyname',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customemailleads',
            name='maincategory',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customemailleads',
            name='maincategoryid',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customemailleads',
            name='roles',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customemailleads',
            name='subcategory',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emailbenchsales',
            name='created_date',
            field=models.TextField(blank=True, default='2023-10-16'),
        ),
    ]
