# Generated by Django 3.2.5 on 2023-09-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_emailbenchsales_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombenchsales',
            name='bench_descriptions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customemailleads',
            name='Email_descriptions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customemailleads',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customemailleads',
            name='contactdetails',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customemailleads',
            name='keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customemailleads',
            name='qualifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customemailleads',
            name='responsibilities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customemailleads',
            name='shortjobdescription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emailbenchsales',
            name='created_date',
            field=models.TextField(blank=True, default='2023-09-28'),
        ),
    ]
