# Generated by Django 3.2.5 on 2023-10-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_emailbenchsales_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aliasdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masteralias', models.TextField(blank=True)),
                ('masteraliascolumn', models.TextField(blank=True)),
                ('masteraliasinput', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='emailbenchsales',
            name='created_date',
            field=models.TextField(blank=True, default='2023-10-24'),
        ),
    ]
