# Generated by Django 3.2.5 on 2023-09-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20230928_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailbenchsales',
            name='created_date',
            field=models.TextField(blank=True, default='2023-09-29'),
        ),
    ]
