# Generated by Django 3.2.5 on 2023-10-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_emailbenchsales_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='benchreparse',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='film',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='film',
            name='contactdetails',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='film',
            name='keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='film',
            name='qualifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='film',
            name='responsibilities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='film',
            name='shortjobdescription',
            field=models.TextField(blank=True),
        ),
    ]
