# Generated by Django 3.2.5 on 2023-10-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_emailbenchsales_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='maincategoryid',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='film',
            name='masteralias',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='film',
            name='masteraliascolumn',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='film',
            name='masteraliasinput',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emailbenchsales',
            name='created_date',
            field=models.TextField(blank=True, default='2023-10-13'),
        ),
    ]
