# Generated by Django 3.2.5 on 2023-10-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_emailbenchsales_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customemailleads',
            name='companyname',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customemailleads',
            name='maincategory',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customemailleads',
            name='maincategoryid',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customemailleads',
            name='roles',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customemailleads',
            name='subcategory',
            field=models.TextField(blank=True),
        ),
    ]
