from django.urls import path 
from  . import views 
from core.views import (Product_view, SnippetList, Leads_view, Emailopp_view, Emailsamplelead_view, Emailbenchsales_view, CustomEmailleads_view, CustomBenchsales_view)

from django.urls import re_path
urlpatterns = [
    path('index/',views.index, name='index'),
    path('getDatapoint/',views.getDatapoint, name='getDatapoint'),
    path('upload/', views.upload_txt, name='upload_txt'),
    path('emailleadupload/', views.emaillead_upload_txt, name='emailleadupload'),
    path('emailbenchsalesupload/', views.emailbenchsalesupload, name='emailbenchsalesupload'),
    path('emailbenchsalesupdate/<int:id>',views.benchsalesupdate,name="emailbenchsalesupdate"),
    path('emailbenchsalesedit/<int:id>',views.emailbenchsalesedit,name="emailbenchsalesedit"),
    path('benchsales/', Emailbenchsales_view.as_view(), name="benchsales"),
    path('customemailleadsupdate/<int:id>',views.customemailleadsupdate,name="customemailleadsupdate"),
    path('customemailleadsview/<int:id>',views.customemailleadsedit,name="customemailleadsview"),
    path('customemailleads/',CustomEmailleads_view.as_view(),name="customemailleads"),
    path('customemailleadscreate/', views.Customemailleadscreate, name="customemailleadscreate"),
    path('customemailleadadd/', views.customemailleadadd, name="customemailleadadd"),

    path('custombenchsalesupdate/<int:id>',views.custombenchsalesupdate,name="custombenchsalesupdate"),
    path('custombenchsalesview/<int:id>',views.custombenchsalesedit,name="custombenchsalesview"),
    path('custombenchsales/',CustomBenchsales_view.as_view(),name="custombenchsales"),
    path('Custombenchsalescreate/', views.Custombenchsalescreate, name="Custombenchsalescreate"),
    path('custombenchsalesadd/', views.custombenchsalesadd, name="custombenchsalesadd"),
    # path('', views.upload_txt, name='upload_txt'),
    # path('retrieve/',views.retrieve,name="retrieve"),
    path('edit/<int:id>',views.edit,name="edit"),
    path('leadedit/<int:id>',views.leadedit,name="leadedit"),
    path('emailnewleadsedit/<int:id>',views.emailsampleleadedit,name="emailnewleadsedit"),
    # path('emailleadedit/<int:id>',views.emailleadedit,name="emailleadedit"),
    path('emailleadoppurtunitiesedit/<int:id>',views.emailleadoppurtunitiesedit,name="emailleadoppurtunitiesedit"),
    path('update/<int:id>',views.update,name="update"),
    path('emailnewleadsupdate/<int:id>',views.sampleleadupdate,name="emailnewleadsupdate"),
    # path('emailleadupdate/<int:id>',views.emailleadupdate,name="emailleadupdate"),
    path('emailleadoppupdate/<int:id>',views.emailleadoppupdate,name="emailleadoppupdate"),
    path('leadupdate/<int:id>',views.leadupdate,name="leadupdate"),
    # path('leadupdate/<int:id>',views.emailleadoppupdate,name="leadupdate"),
    path('delete/<int:id>',views.delete,name="delete"),
    path('opportunities/',views.search, name="search"),
    path('', Product_view.as_view(), name="home"),
    # path('emailhome/', Emailproduct_view.as_view(), name="emailhome"),
    path('emailleadoppurtunities/', Emailopp_view.as_view(), name="emailleadoppurtunities"),
    path('emailnewleads/', Emailsamplelead_view.as_view(), name="emailnewleads"),
    path('retrieve/', Product_view.as_view(), name="retrieve"),
    path('leads/', Leads_view.as_view(), name="leads"),
    path('status/<int:id>/', views.status, name='status'),
    re_path(r'snippets/$', SnippetList.as_view(), name='snippet-list'),
    path('snippets/', SnippetList.as_view(), name="snippet"),
    path('customemailleadsfile/', views.customemailleadsfile, name='customemailleadsfile'),
    path('custombenchsalesfile/', views.custombenchsalesfile, name='custombenchsalesfile'),
    # path('locations/', views.locations, name="locations"),
]