# Generated by Django 3.2.5 on 2023-10-03 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/')),
            ],
        ),
        migrations.CreateModel(
            name='candidateskill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField(blank=True)),
                ('experience', models.TextField(blank=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='candidatereference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referred_by', models.TextField(blank=True)),
                ('referrer_email', models.TextField(blank=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='candidateprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumetext', models.TextField(blank=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('lastname', models.CharField(blank=True, max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=255)),
                ('phone_carrier', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('total_experience', models.TextField(blank=True)),
                ('category', models.TextField(blank=True)),
                ('education', models.TextField(blank=True)),
                ('specialization', models.TextField(blank=True)),
                ('legalstatus', models.CharField(blank=True, max_length=255)),
                ('password', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('zipcode', models.CharField(blank=True, max_length=255)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='candidateprofessional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_summary', models.TextField(blank=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='candidateobjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectives', models.TextField(blank=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='candidateexperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.TextField(blank=True)),
                ('job_title', models.TextField(blank=True)),
                ('joblocation', models.TextField(blank=True)),
                ('job_start_year', models.TextField(blank=True, null=True)),
                ('job_end_year', models.TextField(blank=True, null=True)),
                ('job_start_month', models.TextField(blank=True, null=True)),
                ('job_end_month', models.TextField(blank=True, null=True)),
                ('present', models.TextField(blank=True, null=True)),
                ('Description', models.TextField(blank=True)),
                ('Responsibilites', models.TextField(blank=True)),
                ('Accomplishments', models.TextField(blank=True)),
                ('skillused', models.TextField(blank=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='candidateeducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.TextField(blank=True)),
                ('majordegree', models.TextField(blank=True)),
                ('specializationdegree', models.TextField(blank=True)),
                ('institute', models.TextField(blank=True)),
                ('start_year', models.TextField(blank=True)),
                ('end_year', models.TextField(blank=True)),
                ('institutelocation', models.TextField(blank=True)),
                ('others', models.TextField(blank=True)),
                ('if_others', models.TextField(blank=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='candidatecertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Certification_code', models.TextField(blank=True)),
                ('certification_name', models.TextField(blank=True)),
                ('date_of_certification', models.TextField(blank=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
    ]
