# Generated by Django 3.2.5 on 2023-10-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_candidateexperience_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateexperience',
            name='present',
            field=models.TextField(blank=True, null=True),
        ),
    ]
