# Generated by Django 3.2.5 on 2023-10-09 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_candidateexperience_present'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidatereparser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ResumeParser', models.TextField(blank=True)),
                ('ExperienceParser', models.TextField(blank=True)),
                ('EducationParser', models.TextField(blank=True)),
                ('CertificateParser', models.TextField(blank=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
    ]
